apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: creator-store
resources:
  - ../../base
configMapGenerator:
  - name: creator-store-edge-proxy
    files:
      - default.conf=files/default.conf
  - name: creator-store-proxy-params
    files:
      - proxy_params=files/proxy_params
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: platform.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: creator-store-web
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/0/hostPort
        value: 80
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: edge-proxy-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: proxy-params
          mountPath: /etc/nginx/proxy_params
          subPath: proxy_params
          readOnly: true
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: edge-proxy-config
          configMap:
            name: creator-store-edge-proxy
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: proxy-params
          configMap:
            name: creator-store-proxy-params
