apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: platform.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: creator-store-web
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/ports/0/hostPort
        value: 80
