apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: creator-store
resources:
  - namespace.yaml
  - runtime-config.yaml
  - api.yaml
  - web.yaml
  - policies.yaml
  - storage.yaml
  - ingress.yaml
